/**
 * Pokémon Masters — real named-character portraits (optional override layer).
 *
 * This map is EMPTY by default, so out of the box every named leader / Elite
 * Four / champion / professor uses the gender- and role-appropriate class sprite
 * chosen in config.mjs (npcSpriteMatch). That keeps the system fully
 * self-contained with only the sprites reachable from open GitHub decomps.
 *
 * Pokémon Showdown, however, hosts a real portrait for EVERY named character in
 * every generation (Cynthia, Leon, Nessa, Iono, …). That host is blocked inside
 * the build sandbox, but it is reachable from an ordinary machine. Running
 *
 *     npm run avatars
 *
 * anywhere Showdown is reachable downloads those portraits into assets/trainers/
 * and REWRITES this file to map each character to its real sprite. From then on
 * the world uses the real portraits — and, since the files are vendored into the
 * repo, the game stays self-contained (no run-time network calls).
 *
 * Keyed by the character's lowercase name; value is a file in assets/trainers/.
 * Auto-generated — do not edit by hand (npm run avatars overwrites it).
 */
export const NAMED_AVATARS = {
  "aaron": "avatar_aaron.png",
  "acerola": "avatar_acerola.png",
  "alder": "avatar_alder.png",
  "bea": "avatar_bea.png",
  "blaine": "avatar_blaine.png",
  "blue": "avatar_blue.png",
  "brassius": "avatar_brassius.png",
  "brawly": "avatar_brawly.png",
  "brock": "avatar_brock.png",
  "bruno": "avatar_bruno.png",
  "brycen": "avatar_brycen.png",
  "bugsy": "avatar_bugsy.png",
  "burgh": "avatar_burgh.png",
  "byron": "avatar_byron.png",
  "caitlin": "avatar_caitlin.png",
  "candice": "avatar_candice.png",
  "chuck": "avatar_chuck.png",
  "cilan, chili & cress": "avatar_cress.png",
  "clair": "avatar_clair.png",
  "clay": "avatar_clay.png",
  "clemont": "avatar_clemont.png",
  "crasher wake": "avatar_crasherwake.png",
  "cynthia": "avatar_cynthia.png",
  "diantha": "avatar_diantha.png",
  "drasna": "avatar_drasna.png",
  "drayden": "avatar_drayden.png",
  "elesa": "avatar_elesa.png",
  "erika": "avatar_erika.png",
  "falkner": "avatar_falkner.png",
  "fantina": "avatar_fantina.png",
  "flannery": "avatar_flannery.png",
  "flint": "avatar_flint.png",
  "gardenia": "avatar_gardenia.png",
  "geeta": "avatar_geeta.png",
  "giovanni": "avatar_giovanni.png",
  "glacia": "avatar_glacia.png",
  "gordie": "avatar_gordie.png",
  "grant": "avatar_grant.png",
  "grimsley": "avatar_grimsley.png",
  "grusha": "avatar_grusha.png",
  "hala": "avatar_hala.png",
  "hapu": "avatar_hapu.png",
  "hassel": "avatar_hassel.png",
  "ilima": "avatar_ilima.png",
  "iono": "avatar_iono.png",
  "jasmine": "avatar_jasmine.png",
  "kabu": "avatar_kabu.png",
  "kahili": "avatar_kahili.png",
  "karen": "avatar_karen.png",
  "katy": "avatar_katy.png",
  "kiawe": "avatar_kiawe.png",
  "kofu": "avatar_kofu.png",
  "koga": "avatar_koga.png",
  "korrina": "avatar_korrina.png",
  "lana": "avatar_lana.png",
  "lance": "avatar_lance.png",
  "larry": "avatar_larry.png",
  "lenora": "avatar_lenora.png",
  "leon": "avatar_leon.png",
  "lt. surge": "avatar_ltsurge.png",
  "mallow": "avatar_mallow.png",
  "malva": "avatar_malva.png",
  "marshal": "avatar_marshal.png",
  "maylene": "avatar_maylene.png",
  "milo": "avatar_milo.png",
  "mina": "avatar_mina.png",
  "misty": "avatar_misty.png",
  "morty": "avatar_morty.png",
  "nanu": "avatar_nanu.png",
  "nessa": "avatar_nessa.png",
  "norman": "avatar_norman.png",
  "olivia": "avatar_olivia.png",
  "olympia": "avatar_olympia.png",
  "opal": "avatar_opal.png",
  "piers": "avatar_piers.png",
  "professor birch": "avatar_birch.png",
  "professor elm": "avatar_elm.png",
  "professor juniper": "avatar_juniper.png",
  "professor kukui": "avatar_kukui.png",
  "professor magnolia": "avatar_magnolia.png",
  "professor oak": "avatar_oak.png",
  "professor rowan": "avatar_rowan.png",
  "professor sada / turo": "avatar_sada.png",
  "professor sycamore": "avatar_sycamore.png",
  "pryce": "avatar_pryce.png",
  "raihan": "avatar_raihan.png",
  "ramos": "avatar_ramos.png",
  "rika": "avatar_rika.png",
  "roark": "avatar_roark.png",
  "roxanne": "avatar_roxanne.png",
  "ryme": "avatar_ryme.png",
  "sabrina": "avatar_sabrina.png",
  "shauntal": "avatar_shauntal.png",
  "sidney": "avatar_sidney.png",
  "siebold": "avatar_siebold.png",
  "skyla": "avatar_skyla.png",
  "sophocles": "avatar_sophocles.png",
  "steven": "avatar_steven.png",
  "tate & liza": "avatar_tate.png",
  "tulip": "avatar_tulip.png",
  "valerie": "avatar_valerie.png",
  "viola": "avatar_viola.png",
  "volkner": "avatar_volkner.png",
  "wallace": "avatar_wallace.png",
  "wattson": "avatar_wattson.png",
  "whitney": "avatar_whitney.png",
  "wikstrom": "avatar_wikstrom.png",
  "will": "avatar_will.png",
  "winona": "avatar_winona.png",
  "wulfric": "avatar_wulfric.png",
};
