/**
 * Pokémon Masters — real named-character portraits (optional override layer).
 *
 * This map is EMPTY by default, so out of the box every named leader / Elite
 * Four / champion / professor uses the gender- and role-appropriate class sprite
 * chosen in config.mjs (npcSpriteMatch). That keeps the system fully
 * self-contained with only the sprites reachable from open GitHub decomps.
 *
 * Pokémon Showdown, however, hosts a real portrait for EVERY named character in
 * every generation (Cynthia, Leon, Nessa, Iono, …). That host is blocked inside
 * the build sandbox, but it is reachable from an ordinary machine. Running
 *
 *     npm run avatars
 *
 * anywhere Showdown is reachable downloads those portraits into assets/trainers/
 * and REWRITES this file to map each character to its real sprite. From then on
 * the world uses the real portraits — and, since the files are vendored into the
 * repo, the game stays self-contained (no run-time network calls).
 *
 * Keyed by the character's lowercase name; value is a file in assets/trainers/.
 * Auto-generated — do not edit by hand (npm run avatars overwrites it).
 */
export const NAMED_AVATARS = {
  "aaron": "avatar_aaron.png",
  "acerola": "avatar_acerola.png",
  "alder": "avatar_alder.png",
  "archer": "avatar_archer.png",
  "ariana": "avatar_ariana.png",
  "barry": "avatar_barry.png",
  "bea": "avatar_bea.png",
  "bede": "avatar_bede.png",
  "bianca": "avatar_bianca.png",
  "blaine": "avatar_blaine.png",
  "blue": "avatar_blue.png",
  "brassius": "avatar_brassius.png",
  "brawly": "avatar_brawly.png",
  "brendan": "avatar_brendan.png",
  "brock": "avatar_brock.png",
  "bruno": "avatar_bruno.png",
  "brycen": "avatar_brycen.png",
  "bryony": "avatar_bryony.png",
  "bugsy": "avatar_bugsy.png",
  "burgh": "avatar_burgh.png",
  "byron": "avatar_byron.png",
  "caitlin": "avatar_caitlin.png",
  "calem": "avatar_calem.png",
  "candice": "avatar_candice.png",
  "charon": "avatar_charon.png",
  "cheren": "avatar_cheren.png",
  "chuck": "avatar_chuck.png",
  "cilan, chili & cress": "avatar_cress.png",
  "clair": "avatar_clair.png",
  "clay": "avatar_clay.png",
  "clemont": "avatar_clemont.png",
  "colress": "avatar_colress.png",
  "courtney": "avatar_courtney.png",
  "crasher wake": "avatar_crasherwake.png",
  "cynthia": "avatar_cynthia.png",
  "cyrus": "avatar_cyrus.png",
  "dawn": "avatar_dawn.png",
  "diantha": "avatar_diantha.png",
  "drasna": "avatar_drasna.png",
  "drayden": "avatar_drayden.png",
  "elesa": "avatar_elesa.png",
  "elio": "avatar_elio.png",
  "erika": "avatar_erika.png",
  "ethan": "avatar_ethan.png",
  "faba": "avatar_faba.png",
  "falkner": "avatar_falkner.png",
  "fantina": "avatar_fantina.png",
  "flannery": "avatar_flannery.png",
  "flint": "avatar_flint.png",
  "gardenia": "avatar_gardenia.png",
  "geeta": "avatar_geeta.png",
  "ghetsis": "avatar_ghetsis.png",
  "giovanni": "avatar_giovanni.png",
  "glacia": "avatar_glacia.png",
  "gladion": "avatar_gladion.png",
  "gloria": "avatar_gloria.png",
  "gordie": "avatar_gordie.png",
  "grant": "avatar_grant.png",
  "grimsley": "avatar_grimsley.png",
  "grusha": "avatar_grusha.png",
  "guzma": "avatar_guzma.png",
  "hala": "avatar_hala.png",
  "hapu": "avatar_hapu.png",
  "hassel": "avatar_hassel.png",
  "hau": "avatar_hau.png",
  "hilbert": "avatar_hilbert.png",
  "hilda": "avatar_hilda.png",
  "hop": "avatar_hop.png",
  "hugh": "avatar_hugh.png",
  "ilima": "avatar_ilima.png",
  "iono": "avatar_iono.png",
  "jasmine": "avatar_jasmine.png",
  "jupiter": "avatar_jupiter.png",
  "kabu": "avatar_kabu.png",
  "kahili": "avatar_kahili.png",
  "karen": "avatar_karen.png",
  "katy": "avatar_katy.png",
  "kiawe": "avatar_kiawe.png",
  "kofu": "avatar_kofu.png",
  "koga": "avatar_koga.png",
  "korrina": "avatar_korrina.png",
  "lana": "avatar_lana.png",
  "lance": "avatar_lance.png",
  "larry": "avatar_larry.png",
  "lenora": "avatar_lenora.png",
  "leon": "avatar_leon.png",
  "lt. surge": "avatar_ltsurge.png",
  "lucas": "avatar_lucas.png",
  "lusamine": "avatar_lusamine.png",
  "lyra": "avatar_lyra.png",
  "lysandre": "avatar_lysandre.png",
  "mable": "avatar_mable.png",
  "mallow": "avatar_mallow.png",
  "malva": "avatar_malva.png",
  "marnie": "avatar_marnie.png",
  "mars": "avatar_mars.png",
  "marshal": "avatar_marshal.png",
  "matt": "avatar_matt.png",
  "may": "avatar_may.png",
  "maylene": "avatar_maylene.png",
  "milo": "avatar_milo.png",
  "mina": "avatar_mina.png",
  "misty": "avatar_misty.png",
  "morty": "avatar_morty.png",
  "nanu": "avatar_nanu.png",
  "nate": "avatar_nate.png",
  "nessa": "avatar_nessa.png",
  "norman": "avatar_norman.png",
  "oleana": "avatar_oleana.png",
  "olivia": "avatar_olivia.png",
  "olympia": "avatar_olympia.png",
  "opal": "avatar_opal.png",
  "penny": "avatar_penny.png",
  "petrel": "avatar_petrel.png",
  "piers": "avatar_piers.png",
  "plumeria": "avatar_plumeria.png",
  "professor birch": "avatar_birch.png",
  "professor elm": "avatar_elm.png",
  "professor juniper": "avatar_juniper.png",
  "professor kukui": "avatar_kukui.png",
  "professor magnolia": "avatar_magnolia.png",
  "professor oak": "avatar_oak.png",
  "professor rowan": "avatar_rowan.png",
  "professor sada / turo": "avatar_sada.png",
  "professor sycamore": "avatar_sycamore.png",
  "proton": "avatar_proton.png",
  "pryce": "avatar_pryce.png",
  "raihan": "avatar_raihan.png",
  "ramos": "avatar_ramos.png",
  "red": "avatar_red.png",
  "rika": "avatar_rika.png",
  "roark": "avatar_roark.png",
  "rood": "avatar_rood.png",
  "rosa": "avatar_rosa.png",
  "rose": "avatar_rose.png",
  "roxanne": "avatar_roxanne.png",
  "ryme": "avatar_ryme.png",
  "sabrina": "avatar_sabrina.png",
  "saturn": "avatar_saturn.png",
  "selene": "avatar_selene.png",
  "serena": "avatar_serena.png",
  "shauntal": "avatar_shauntal.png",
  "shelly": "avatar_shelly.png",
  "sidney": "avatar_sidney.png",
  "siebold": "avatar_siebold.png",
  "silver": "avatar_silver.png",
  "skyla": "avatar_skyla.png",
  "sophocles": "avatar_sophocles.png",
  "steven": "avatar_steven.png",
  "tabitha": "avatar_tabitha.png",
  "tate & liza": "avatar_tate.png",
  "tulip": "avatar_tulip.png",
  "valerie": "avatar_valerie.png",
  "victor": "avatar_victor.png",
  "viola": "avatar_viola.png",
  "volkner": "avatar_volkner.png",
  "wallace": "avatar_wallace.png",
  "wally": "avatar_wally.png",
  "wattson": "avatar_wattson.png",
  "whitney": "avatar_whitney.png",
  "wikstrom": "avatar_wikstrom.png",
  "will": "avatar_will.png",
  "winona": "avatar_winona.png",
  "wulfric": "avatar_wulfric.png",
  "xerosic": "avatar_xerosic.png",
  "zinzolin": "avatar_zinzolin.png",
};
